# HOW TO USE:
# The purpose of this docker-compose is to setup our application which is
# dependent on the `MongoDB` database running concurrently with this
# server for developer purposes. This configuration has hot-reloading activated.
#
# $ docker-compose -p workery -f dev.docker-compose.yml up   #
#

services:
  s3:
    container_name: workery_s3
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - s3_data:/data
    environment:
      - MINIO_REGION_NAME=${WORKERY_BACKEND_AWS_REGION}
      - MINIO_ROOT_USER=${WORKERY_BACKEND_AWS_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${WORKERY_BACKEND_AWS_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=${WORKERY_BACKEND_AWS_BUCKET_NAME}
    command: server --console-address ":9001" /data

  # The purpose of this service is to store our application data.
  db:
    container_name: workery_mongodb
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--quiet", "--logpath", "/dev/null"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: unless-stopped
    logging:
      driver: none

  mongo-express:
    container_name: workery_mongodb_admin
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=db
        - ME_CONFIG_MONGODB_PORT=27017
    ports:
        - '8081:8081'
    depends_on:
      - "db"
    links:
      - "db"
    restart: unless-stopped
    logging:
      driver: none

  # The main application.
  app:
    container_name: workery_backend_app
    stdin_open: true
    environment:
        WORKERY_BACKEND_IP: 0.0.0.0
        WORKERY_BACKEND_PORT: 8000
        WORKERY_BACKEND_HMAC_SECRET: ${WORKERY_BACKEND_HMAC_SECRET}
        WORKERY_BACKEND_HAS_DEBUGGING: ${WORKERY_BACKEND_HAS_DEBUGGING}
        WORKERY_BACKEND_CACHE_URI: mongodb://db:27017/?replicaSet=rs0
        WORKERY_BACKEND_DB_URI: ${WORKERY_BACKEND_DB_URI}
        WORKERY_BACKEND_DB_NAME: ${WORKERY_BACKEND_DB_NAME}
        WORKERY_BACKEND_AWS_ACCESS_KEY: ${WORKERY_BACKEND_AWS_ACCESS_KEY}
        WORKERY_BACKEND_AWS_SECRET_KEY: ${WORKERY_BACKEND_AWS_SECRET_KEY}
        WORKERY_BACKEND_AWS_ENDPOINT: ${WORKERY_BACKEND_AWS_ENDPOINT}
        WORKERY_BACKEND_AWS_REGION: ${WORKERY_BACKEND_AWS_REGION}
        WORKERY_BACKEND_AWS_BUCKET_NAME: ${WORKERY_BACKEND_AWS_BUCKET_NAME}
        WORKERY_BACKEND_AWS_S3_FORCE_PATH_STYLE: ${WORKERY_BACKEND_AWS_S3_FORCE_PATH_STYLE}
        WORKERY_BACKEND_INITIAL_ADMIN_EMAIL: ${WORKERY_BACKEND_INITIAL_ADMIN_EMAIL} # Required email for root admin when project starts up
        WORKERY_BACKEND_INITIAL_ADMIN_PASSWORD: ${WORKERY_BACKEND_INITIAL_ADMIN_PASSWORD} # Required password for root admin when project starts up
        WORKERY_BACKEND_INITIAL_ADMIN_ORG_NAME: ${WORKERY_BACKEND_INITIAL_ADMIN_ORG_NAME}
        WORKERY_BACKEND_API_DOMAIN_NAME: ${WORKERY_BACKEND_API_DOMAIN_NAME}
        WORKERY_BACKEND_APP_DOMAIN_NAME: ${WORKERY_BACKEND_APP_DOMAIN_NAME}
        AWS_ACCESS_KEY: ${WORKERY_BACKEND_AWS_ACCESS_KEY} # AWS SDK requires this exact name.
        AWS_SECRET_KEY: ${WORKERY_BACKEND_AWS_SECRET_KEY} # AWS SDK requires this exact name.
        AWS_REGION: ${WORKERY_BACKEND_AWS_REGION}         # AWS SDK requires this exact name.
        WORKERY_BACKEND_MAILGUN_API_KEY: ${WORKERY_BACKEND_MAILGUN_API_KEY}
        WORKERY_BACKEND_MAILGUN_DOMAIN: ${WORKERY_BACKEND_MAILGUN_DOMAIN}
        WORKERY_BACKEND_MAILGUN_API_BASE: ${WORKERY_BACKEND_MAILGUN_API_BASE}
        WORKERY_BACKEND_MAILGUN_SENDER_EMAIL: ${WORKERY_BACKEND_MAILGUN_SENDER_EMAIL}
        WORKERY_BACKEND_PDF_BUILDER_DATA_DIRECTORY_PATH: ${WORKERY_BACKEND_PDF_BUILDER_DATA_DIRECTORY_PATH}
        WORKERY_BACKEND_PDF_BUILDER_ASSOCIATE_INVOICE_PATH: ${WORKERY_BACKEND_PDF_BUILDER_ASSOCIATE_INVOICE_PATH}
        WORKERY_BACKEND_APP_ENABLE_2FA_ON_REGISTRATION: ${WORKERY_BACKEND_APP_ENABLE_2FA_ON_REGISTRATION}
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
      - s3
    links:
      - db
      - s3
    volumes: # Connect the local filesystem with the docker filesystem. DO NOT REMOVE.
      - ./:/go/src/github.com/over55/monorepo/cloud/workery-backend # IMPORTANT: Required for hotreload via `CompileDaemon`.

volumes:
    mongodb_data:
    mongodb_config:
    s3_data:
