# HOW TO USE:
# $ docker-compose -p workery -f docker-compose.yml up   #
#

services:
  caddy:
    container_name: workery_backend_caddy
    image: 'caddy:2-alpine'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '$PWD/Caddyfile:/etc/caddy/Caddyfile'
      - 'caddy_data:/data'
      - 'caddy_config:/config'
    networks:
      - web
      - caddy_internal

  # The purpose of this service is to store our application data.
  db:
    container_name: workery_mongodb
    image: mongo:6.0.5-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: unless-stopped
    logging:
      driver: none
    networks:
      - caddy_internal

  # The main application.
  app:
    container_name: workery_backend_app
    image: 'over55/workery-backend:latest'
    stdin_open: true
    restart: unless-stopped
    environment:
        WORKERY_BACKEND_IP: 0.0.0.0
        WORKERY_BACKEND_PORT: 8000
        WORKERY_BACKEND_HMAC_SECRET: ${WORKERY_BACKEND_HMAC_SECRET}
        WORKERY_BACKEND_HAS_DEBUGGING: ${WORKERY_BACKEND_HAS_DEBUGGING}
        WORKERY_BACKEND_DB_URI: ${WORKERY_BACKEND_DB_URI}
        WORKERY_BACKEND_DB_NAME: ${WORKERY_BACKEND_DB_NAME}
        WORKERY_BACKEND_CACHE_URI: ${WORKERY_BACKEND_CACHE_URI}
        WORKERY_BACKEND_CACHE_PASSWORD: ${WORKERY_BACKEND_CACHE_PASSWORD}
        WORKERY_BACKEND_AWS_ACCESS_KEY: ${WORKERY_BACKEND_AWS_ACCESS_KEY}
        WORKERY_BACKEND_AWS_SECRET_KEY: ${WORKERY_BACKEND_AWS_SECRET_KEY}
        WORKERY_BACKEND_AWS_ENDPOINT: ${WORKERY_BACKEND_AWS_ENDPOINT}
        WORKERY_BACKEND_AWS_REGION: ${WORKERY_BACKEND_AWS_REGION}
        WORKERY_BACKEND_AWS_BUCKET_NAME: ${WORKERY_BACKEND_AWS_BUCKET_NAME}
        WORKERY_BACKEND_INITIAL_ADMIN_EMAIL: ${WORKERY_BACKEND_INITIAL_ADMIN_EMAIL} # Required email for root admin when project starts up
        WORKERY_BACKEND_INITIAL_ADMIN_PASSWORD: ${WORKERY_BACKEND_INITIAL_ADMIN_PASSWORD} # Required password for root admin when project starts up
        WORKERY_BACKEND_INITIAL_ADMIN_ORG_NAME: ${WORKERY_BACKEND_INITIAL_ADMIN_ORG_NAME}
        WORKERY_BACKEND_API_DOMAIN_NAME: ${WORKERY_BACKEND_API_DOMAIN_NAME}
        WORKERY_BACKEND_APP_DOMAIN_NAME: ${WORKERY_BACKEND_APP_DOMAIN_NAME}
        AWS_ACCESS_KEY: ${WORKERY_BACKEND_AWS_ACCESS_KEY} # AWS SDK requires this exact name.
        AWS_SECRET_KEY: ${WORKERY_BACKEND_AWS_SECRET_KEY} # AWS SDK requires this exact name.
        AWS_REGION: ${WORKERY_BACKEND_AWS_REGION}         # AWS SDK requires this exact name.
        WORKERY_BACKEND_MAILGUN_API_KEY: ${WORKERY_BACKEND_MAILGUN_API_KEY}
        WORKERY_BACKEND_MAILGUN_DOMAIN: ${WORKERY_BACKEND_MAILGUN_DOMAIN}
        WORKERY_BACKEND_MAILGUN_API_BASE: ${WORKERY_BACKEND_MAILGUN_API_BASE}
        WORKERY_BACKEND_MAILGUN_SENDER_EMAIL: ${WORKERY_BACKEND_MAILGUN_SENDER_EMAIL}
        WORKERY_BACKEND_PDF_BUILDER_DATA_DIRECTORY_PATH: ${WORKERY_BACKEND_PDF_BUILDER_DATA_DIRECTORY_PATH}
        WORKERY_BACKEND_PDF_BUILDER_ASSOCIATE_INVOICE_PATH: ${WORKERY_BACKEND_PDF_BUILDER_ASSOCIATE_INVOICE_PATH}
        WORKERY_BACKEND_APP_ENABLE_2FA_ON_REGISTRATION: ${WORKERY_BACKEND_APP_ENABLE_2FA_ON_REGISTRATION}
    depends_on:
      - db
    links:
      - db
    volumes:
      - app_data:/data
    networks:
      - caddy_internal

networks:
  web:
    external: true
  caddy_internal:
    external: false
    driver: bridge

volumes:
  app_data:
    external: true
  mongodb_data:
    external: true
  mongodb_config:
    external: true
  caddy_data:
    external: true
  caddy_config:
    external: true
